@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDMzMDUzMDZ9.QO4-LwObgCMduWmw-6e1Y0pfi25WV7scc5GvBCRZ0I0

@domain =


### login(gets us a jwt)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "adam@gmail.com",
  "password": "password"
}
### USER CREATE
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Jasons Crabs",
  "email": "jcrabs@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

###
#ORDER CREATE
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "product_id": 3,
  "quantity": 5
}

###
#Order SHOW
GET http://localhost:3000/orders/3
# Authorization: Bearer {{ jwt }}

###
#ORDER INDEX
GET http://localhost:3000/orders
Authorization: Bearer {{ jwt }}

