POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "adam@gmail.com",
  "password": "password"
}
###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Adams Reef",
  "email": "adam@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

###
#ORDER CREATE
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDMyMjI4ODF9.jXooa4LG8JOz9zWCM5y2M6vUtwZDRD-kky2DPI6E4KA

{
  "product_id": 1,
  "quantity": 3
}

###
#Order SHOW
GET http://localhost:3000/orders/1

###
#ORDER INDEX
GET http://localhost:3000/orders